spring:
  application:
    name: application

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:project-management-system}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:default_user}
    password: ${MAIL_PASSWORD:default_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_SECRET:my-secret-key}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  liquibase:
    change-log: classpath:/config/db/liquibase/master.xml
    #drop-first: true
    enabled: false

  server:
    port: 8080

  api:
    security:
      token:
        secret: ${TOKEN_SECRET_KEY:your-secret-key}